"""
Random phrases with emoji for the ScrollMaster display.
Each phrase is approximately 25 words with 3-10 emoji.
"""

PHRASES = [
    "🚀 Ready for an amazing adventure today! Let's blast off into the stratosphere and make incredible memories together. The sky is not the limit! ✨🌟",
    "🎉 Life is a beautiful celebration filled with wonderful moments and incredible opportunities! Dance through the day with joy and spread happiness everywhere you go! 🎊💫🌈",
    "💡 Brilliant ideas are born from curiosity and determination! Keep exploring, keep learning, and watch as your dreams transform into reality before your very eyes! ✨🚀🌟",
    "⭐ You shine brighter than all the stars in the universe! Your unique light brings warmth and inspiration to everyone around you! Keep glowing magnificently! 🌟💫✨",
    "🔥 Ignite your passion and let it fuel your journey toward greatness! Every challenge is an opportunity to rise, grow stronger, and achieve the impossible! 💪🚀🎯",
    "💯 Perfection comes from dedication, hard work, and believing in yourself! You've got everything it takes to accomplish amazing things today and every single day! 🌟✨🎉",
    "🌈 After every storm comes a beautiful rainbow of hope and new possibilities! Embrace the colors of life and paint your world with joy and positivity! ☀️💕🌸",
    "☕ Morning coffee fuels the soul and awakens the spirit for another wonderful day of adventures, creativity, and making beautiful memories with loved ones! ☕✨😊",
    "� Pizza brings people together in the most delicious way possible! Share a slice of happiness and create unforgettable moments around the table tonight! 🍕❤️🎉",
    "� Level up in life just like you level up in games! Face challenges head-on, learn from mistakes, and unlock your greatest potential every single day! 🚀💪🏆",
    "🌸 Spring brings renewal, fresh starts, and endless possibilities blooming everywhere! Embrace change, grow beautifully, and flourish in all that you do today! 🌺🌼💕",
    "� Music is the universal language that touches hearts and lifts spirits! Let the rhythm guide you through life's beautiful dance of joy and wonder! 🎶✨💃",
    "� Champions are made through persistence, courage, and unwavering belief! You have the strength within you to conquer any mountain and achieve greatness today! 💪🚀🌟",
    "� Sweet dreams bring peace, rest, and magical adventures in the realm of sleep! Tomorrow awaits with new opportunities and wonderful surprises just for you! ✨💫😴",
    "☀️ Good morning sunshine! Today is a brand new canvas waiting for your unique colors, ideas, and the beautiful masterpiece only you can create! 🎨🌟💛",
    "🎸 Rock and roll through life with passion, energy, and unstoppable enthusiasm! Make some noise, shake things up, and live every moment to the absolute fullest! 🎵🔥💫",
    "� Life is sweet like ice cream on a hot summer day! Savor every flavor, enjoy the little moments, and create memories that melt your heart! 💕🌞😋",
    "🌊 Ride the waves of change with courage and grace! Navigate through life's tides confidently, knowing that every wave brings you closer to your dreams! 🏄✨💙",
    "� All the world's a stage and you're the star of your own incredible story! Perform with passion, authenticity, and make every scene absolutely memorable! 🌟�💫",
    "� Celebrate life's sweet moments with joy, gratitude, and those you love most! Every day is a gift worth savoring like your favorite delicious dessert! 🎂❤️🎉",
    "🌍 Our beautiful planet needs our love, care, and protection every single day! Together we can make a difference and create a sustainable future for everyone! 🌱💚🌎",
    "� Focus on your goals with laser precision and unwavering determination! Hit your targets one by one and watch your dreams become your reality step by step! 🚀💪🏆",
    "🍔 Grill master mode activated! Fire up the barbecue and create mouthwatering memories with friends, family, and all the delicious flavors of summer fun! 🔥🍟😋",
    "🌺 Embrace the island vibes and let your worries drift away on gentle tropical breezes! Life is better with sunshine, palm trees, and a relaxed mindset! 🌴☀️💕",
    "� Step right up to the greatest show on earth called life! Experience wonder, excitement, and amazing surprises around every corner of your journey today! 🎠✨🎉",
    "� Your inner light shines so brilliantly that it illuminates the path for others! Never dim your sparkle because the world needs your unique radiance today! ✨💫🌈",
    "� Creativity flows through you like a river of endless possibilities! Paint your dreams, sculpt your future, and design a life that's a true masterpiece! 🖌️�💡",
    "� Berry delicious adventures await you today! Pick the sweetest moments, savor life's flavors, and fill your basket with joy, love, and wonderful memories! 💕🌸😊",
    "� Jazz up your day with spontaneity, rhythm, and smooth moves that make life swing beautifully! Improvise, create, and let your soul sing with joy! 🎵✨💃",
    "🌻 Follow the sun and bloom where you're planted! Grow tall, stay rooted in your values, and spread seeds of kindness everywhere you go today! 🌞💛🌱",
    "� Lucky charms and good fortune follow those who believe, work hard, and stay positive through all of life's wonderful adventures and challenging moments! ✨🌈💚",
    "🎬 Lights, camera, action! Your life is an epic movie and you're both the director and the star! Make it a blockbuster worth watching again and again! 🌟🎥🍿",
    "� When life gives you lemons, make lemonade, lemon pie, and lemon everything! Turn challenges into opportunities and sourness into sweetness every single day! 🍹💛😊",
    "🌹 Stop and smell the roses along your journey through life! Beauty surrounds you everywhere when you pause to appreciate the little wonderful things daily! 💕🌸✨",
    "� An apple a day keeps the doctor away and keeps your spirit bright! Nourish your body, mind, and soul with healthy choices and positive vibes! 🍏💚😊",
    "� Sweet as honey and twice as golden, your kindness makes the world a better place! Spread sweetness wherever you go and watch it multiply beautifully! 🐝💛✨",
    "� Party like there's no tomorrow but plan like you'll live forever! Celebrate every victory, cherish every moment, and create memories that last a lifetime! �🥳💫",
    "� Life is like a candy store filled with endless sweet possibilities! Choose your favorites, try new flavors, and enjoy every delightful moment to the fullest! 🍭💕😋",
    "� Game on! Level up your skills, collect all the achievements, and remember that every reset is just another chance to play better than before! �️🏆✨",
    "� Shooting stars carry wishes across the night sky! Make your dreams known to the universe and watch as magic unfolds in the most unexpected ways! ✨💫🌙",
    "🍕 Pizza night is family night! Gather around, share slices and stories, and create warm memories that you'll cherish forever in your heart! ❤️🍕😊",
    "� Chase rainbows and catch dreams along the way! Every color represents a different blessing in your life worth celebrating with gratitude and pure joy! 🌟💕☀️",
    "💪 Strength comes not from physical capacity but from an indomitable will and fierce determination! Push your limits and discover just how powerful you are! 🔥�💯",
    "� Dance like nobody's watching and sing like nobody's listening! Express yourself freely, embrace your rhythm, and let music fill your soul with pure happiness! 💃🎶✨",
    "� Moon and stars light the path when darkness falls! Trust the journey even when you can't see the road ahead clearly because magic happens at night! ✨💫🌟",
    "� Life is sweeter when shared with those you love most! Bake memories, frost them with kindness, and serve generous portions of joy to everyone! 🎂❤️😊",
    "🏖️ Beach vibes and ocean tides bring peace to the soul! Let worries wash away with each wave and soak up the sunshine of life's simple pleasures! 🌊☀️🌴",
    "� Bulls-eye! You hit the target when you aim with intention, focus with clarity, and shoot your shot with confidence and unwavering belief in yourself! 🏹💪🌟",
    "� Donut worry, be happy! Life's too short to stress about the small stuff when there are sprinkles to enjoy and sweet moments to savor today! 😊💕🍩",
    "� Growth happens when you step outside your comfort zone and embrace the unknown! Plant seeds of courage today and watch them bloom into greatness tomorrow! 🌿💚✨",
    "� The circus of life brings thrills, chills, and spectacular moments! Enjoy the show, take risks on the trapeze, and laugh like a clown every day! 🤡🎭🎠",
    "� Grape expectations lead to wonderful surprises! Believe in the best, work toward excellence, and watch your life transform into something truly extraordinary and beautiful! 💜✨🌟",
    "� Sunshine follows you wherever you go when you carry light within your heart! Radiate warmth, spread brightness, and illuminate the lives of others beautifully! ☀️💛😊",
    "� Turn it up to eleven and rock your world with passion, purpose, and powerful energy! Make noise, break barriers, and live life like the rockstar you are! 🔥🎵💫",
    "� Peachy keen and absolutely wonderful describes you perfectly! Embrace your sweetness, share your juiciness with the world, and stay fresh always! 🍑💕😊",
    "� One world, one love, one beautiful human family sharing this incredible planet together! Spread kindness, build bridges, and celebrate our amazing diversity today! 💚🌎✨",
    "🎨 Paint the town with your unique colors and creative spirit! Express yourself boldly, make art from life, and turn the ordinary into something extraordinary! 🖌️🌈💡",
    "� Cookie monster mode activated! Indulge in life's treats, share sweetness with others, and remember that you deserve all the delicious goodness coming your way! 🍪😋💕",
    "� Aloha spirit means love, compassion, and treating everyone like family! Embrace this beautiful philosophy and watch your world transform into paradise on earth today! 🌴💕✨",
    "� Break a leg and steal the show! Your performance in life deserves a standing ovation, so give it everything you've got and shine brilliantly! 👏🌟💫",
    "🔥 On fire and unstoppable today! Your energy, passion, and determination create sparks that ignite possibilities and light up the world around you magnificently! 💪🚀✨",
    "� Blossom beautifully in your own time and in your own unique way! There's no rush, no competition, just your personal journey toward becoming your best self! 🌺💕🦋",
    "� Trumpet the good news and celebrate all your victories, big and small! Every accomplishment deserves recognition, and you deserve to feel proud of yourself today! 🎉🏆✨",
    "🍍 Pineapple express brings tropical vibes and exotic adventures your way! Stay golden, stand tall with your crown, and spread sweet vibes everywhere you wander! 👑💛🌴",
    "🌷 Tulip time means spring has sprung and new beginnings are blooming everywhere! Embrace fresh starts, plant new dreams, and grow beautiful possibilities daily! 🌼💕🌱",
    "� Four-leaf clovers and lucky stars align when you combine hard work with positive thinking! Create your own luck through dedication, kindness, and optimism! ✨💚🌟",
    "� Take two and action! Every mistake is just another take in your movie, so don't give up until you nail the perfect scene! 🎥🌟💪",
    "� Go with the flow but don't be afraid to make waves! Life's currents take you places, but you're the one steering your ship! 🚢💙✨",
    "� Chill vibes only for the rest of the day! Take it easy, stay cool, and let life's stress melt away like ice cream! 🍨😎💕",
    "� Greatest show on earth is happening right now in your life! Marvel at the wonder, enjoy the spectacle, and be the ringmaster! 🎠🎭�",
    "� Summer sweetness and watermelon dreams make life refreshing! Bite into juicy moments, spit out the seeds of doubt, stay hydrated with joy! 🌞💕😋",
    "� Daisy days are the best days filled with simple pleasures and pure happiness! Pick flowers, make wishes, and enjoy life's gentle beauty! 🌸💛✨",
    "� Music to my ears describes the sound of your laughter and the rhythm of your heartbeat! Keep making beautiful melodies with your life! 🎶❤️😊",
    "� Going bananas with excitement for all the amazing things coming your way! Stay energized, stay positive, and appeal to your adventurous side! 🍌😄💛",
    "� Fresh and green like morning dew on spring grass! Breathe in new possibilities, exhale old worries, and grow naturally into greatness! 🌱💚✨",
    "� Right on target with your goals and dreams! Keep your eyes on the prize, stay focused on what matters, and victory will be yours! 🏆💪🌟",
    "� Cherry on top of an already wonderful day! Little extras make life special, so appreciate the finishing touches and sweet surprises! 🍒❤️😊",
    "� Stellar performance in everything you do makes the universe proud! Your brilliance lights up galaxies, so keep shining like the star you are! ✨💫🌌",
    "� Masterpiece mode activated! You're creating a work of art with your life choices, actions, and the love you share with the world! 🖌️🌈💕",
    "🍇 Vine and dandy feeling describes your amazing energy today! Stay connected to your roots while reaching for the sky with confidence! 🍇💜✨",
    "� Island time means no worries, no stress, just pure relaxation and tropical tranquility! Let your mind drift to paradise and stay there! 🏝️☀️💙",
    "� Strum away all your worries and play the soundtrack of your dreams! Life is better with music, rhythm, and a guitar in hand! 🎵🔥✨",
    "🍎 Apple of my eye describes how special you are to everyone lucky enough to know you! Stay sweet, crisp, and absolutely delightful! 🍏❤️😊",
    "� Dream big, reach for the stars, and never stop believing in the magic of your potential! The universe has incredible plans for you! ✨💫🌟",
    "🎉 Celebrate good times because they're happening right now all around you! Joy is everywhere when you open your eyes to life's blessings! 🎊🥳💕",
    "🍬 Candy crush level expert in the game of life! Collect sweet moments, match them with gratitude, and enjoy the delicious rewards! 🍭💕😋",
    "🌈 Over the rainbow lies a land where dreams come true and wishes are granted! Take the leap and discover your own magical Oz! 🌟💛✨",
    "🎭 Life's a stage and you're giving the performance of a lifetime! Act with passion, speak your truth, and take a bow gracefully! 👏🌟💫",
    "🍕 Pizza is life, love, and everything good in this world combined! Share slices of happiness and make every meal memorable with friends! 🍕❤️🎉",
    "� Save the planet one small action at a time and inspire others to join! Together we're powerful, united we're unstoppable for good! 🌱💚🌎",
    "🎮 Level up in real life by learning new skills, taking on challenges, and never giving up even when the game gets tough! 🕹️💪🏆",
    "� Berry happy describes your mood when you count your blessings and appreciate all the sweet things life offers you every single day! 💕🌸😊",
    "� Sunflower smiles light up the room and make everyone around you feel warm, welcome, and wonderful! Keep spreading that golden joy! ☀️💛😊",
    "� Lights, camera, action on this beautiful day! Direct your life movie with intention, starring yourself as the hero you were born to be! 🎥🌟💫",
    "� Sweet treats ahead on your journey through life! Indulge in joy, savor happy moments, and remember you deserve all the goodness! 🎂💕😋",
    "� Into the woods we go to find peace, adventure, and ourselves! Nature heals, inspires, and reminds us what truly matters in life! 🌿💚✨",
    "� Spooky season brings costumes, candy, and creative fun for everyone! Embrace the magic, scare up some laughter, and enjoy the thrills! 👻🍬🎉",
    "� Autumn leaves falling create nature's beautiful carpet of gold, orange, and red! Embrace change like the seasons do with grace! 🍂🧡✨",
    "❄️ Winter wonderland transforms the world into a sparkling magical kingdom! Build snowmen, make angels, and warm your heart with love! ⛄💙☃️",
    "� Beach paradise awaits with crystal waters, soft sand, and endless sunshine! Pack your bags for adventure or just dream about it! 🏖️☀️💙",
    "� Holiday cheer spreads joy, love, and magical moments throughout the season! Celebrate traditions, create new memories, and give generously to all! 🎅🎁✨",
    "� Rose all day describes your elegant approach to life's challenges and opportunities! Stay classy, beautiful, and sweetly fragrant in all you do! 💕🌸✨",
    "� Make a wish on your special day and blow out the candles! Dreams come true when you believe, work hard, and celebrate yourself! 🎉🎈💫",
]
